### ISSUE TITLE
bashing transients in place is specifically warned against in the documentation

### ISSUE THREAD

**Issue by hiredman** [clojure-finance/clojure-heap#1]
transients are not just mutable collections with a different name, if you treat them like that your code will run incorrectly.

transient operations like conj! may mutate the existing transient, or return a new value, so you cannot just ignore the return value.

**Comment by hiredman** [comment]
https://clojure.org/reference/transients#_how_they_work

**Comment by hkulyc** [comment]
Thank you for pointing this out. Actually in the pre-release, we did utilize the return value of the transient. However then in the optimization, we found that the return value and the input are the same, so we ignored all the return values. Sorry that we did not find this action is against the transient norms. We have reverted the version back to the “return value” one.
#[82038b5](https://github.com/clojure-finance/clojure-heap/commit/82038b5a90b21a5aec927399cbb34dcdb279fcbc)
